name: huggingface
channels:
    - pytorch
dependencies:
  - python=3.9
  - pip
  - pip:
    - ipywidgets
    - transformers
    - sentencepiece
  - conda
  - conda:
    - ipykernel
    - pytorch
    - torchvision
    - torchaudio
    - torchserve
    - cudatoolkit=11.3
    - scikit-learn
    - matplotlib